apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: exercises-2
  namespace: default
spec:
  initContainers:
  - name: box
    image: busybox
    command: ["wget","-O", "/work-dir/index.html", "http://neverssl.com/online"]
    volumeMounts:
      - mountPath: /work-dir
        name: vol
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: vol
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
    - name: vol
      emptyDir: {}
status: {}
