apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: busybox
    resources: {}
    volumeMounts:
    - mountPath: /etc/foo
      name: cache-volume
  - name: busybox-2
    args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    resources: {}
    volumeMounts:
    - mountPath: /etc/foo
      name: cache-volume
  volumes:
    - name: cache-volume
      emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
