apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
  namespace: default
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - ls /notexist
    image: busybox
    name: pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}