apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    access: granted
  name: pod
spec:
  containers:
  - image: nginx
    name: pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
