apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
  namespace: default
spec:
  containers:
  - args:
    - sh
    - -c
    - echo hello;sleep 3600
    image: busybox
    name: busybox
    resources: {}
  - args:
    - sh
    - -c
    - echo hello;sleep 3600
    image: busybox
    name: busybox-1
    resources: {}

  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
