apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
  namespace: default
spec:
  containers:
  - args:
    - sh
    - -c
    - i=0; while true; do echo "i:i:(date)"; i=$((i+1)); sleep 1; done
    image: busybox
    name: pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
