apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod
  name: pod
  namespace: default
spec:
  containers:
  - image: busybox
    name: pod
    resources: {}
    livenessProbe:
      exec:
        command:
        - ls
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}