apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: foo
  name: foo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 6262
  selector:
    app: foo
status:
  loadBalancer: {}
