apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod
  name: pod
  namespace: default
spec:
  containers:
  - image: nginx
    name: pod
    ports:
      - containerPort: 80
    resources: {}
    livenessProbe:
      initialDelaySeconds: 5
      periodSeconds: 5
      exec:
        command:
        - ls
    readinessProbe:
      httpGet:
        path: /
        port: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}