apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: busybox-pods
  namespace: default
spec:
  containers:
  - command:
    - /bin/sh 
    - -c 
    - 'echo hello; sleep 3600'
    image: busybox
    name: pod
    resources: {}
  - command:
    - /bin/sh 
    - -c 
    - 'echo hello; sleep 3600'
    image: busybox
    name: pod-1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}