apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: busybox
    resources: {}
    volumeMounts:
        - mountPath: /etc/foo
          name: volume
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: mypvc
status: {}
